[package]
name = "pq-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
crossbeam-channel = "0.5.15"
pq-sync = { path="../pq-sync" }
